---
title: "Defining your SEQopts()"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Defining your SEQopts()}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Behind SEQopts()

`SEQopts()` provides the primary API to changing internal options of `SEQuential()`. While the documentation should go over their use, we will expand on them here in greater detail:

## The options

### General Options

| Option Name | Description | Input Type | Example |
|------------|------------------------------------|------------|------------|
| parallel | Whether the bootstrapping should be run in parallel | Boolean | TRUE |
| nthreads | Number of threads to use for data.table manipulations | Integer | 16L |
| ncores | Number of cores to use in parallel multisession | Integer | 8L |
| bootstrap | Whether bootstrapping should take place | Boolean | TRUE |
| bootstrap.nboot | Number of bootstraps to run in addition to the full model | Integer | 100L |
| bootstrap.sample | Subsample of data to use when bootstrapping | Float [0, 1] | 0.8 |
| seed | Starting seed for random number generators | Integer | 1636 |
| followup.min | Minimum value of followup per trial | Numeric | 0 |
| followup.max | Maximum value of followup per trial | Numeric | 60 |
| survival.max | Maximum value for Risk/Survival curves | Numeric | 60 |
| followup.include | Whether to include 'followup' and 'followup\^2' in outcome models | Boolean | TRUE |
| trial.include | Whether to include 'trial' and 'trial\^2' in outcome models | Boolean | TRUE |
| covariates | If provided, forces covariates for outcome models | Char | "X1+X2\*X3+X4" |
| hazard | Whether to estimate the hazard ratio | Boolean | FALSE |
| calculate.var | Whether to calculate the robust standard errors for the outcome model | Boolean | FALSE |
| subgroup | Column name for subgroup analysis | Char | "sex" |
| selection.random | Whether to randomly select IDs with replacement to run analysis | Boolean | FALSE |
| selection.prob | Subsample of total IDs to select | Float [0, 1] | 0.8 |
| followup.class | Whether to expand followup values to an indicator matrix | Boolean | FALSE |
| followup.spline | Whether to format followup values to a spline | Boolean | FALSE |
| multinomial | Whether to expect more than 2 treatment types | Boolean | FALSE |
| treat.level | Treatment levels to compare | List | list(0, 1) |
| km.curves | Whether to estimate kaplan meier survival curves and data | Boolean | TRUE |
| compevent | Column name for competing event variable | Char | "LTFU" |
| data.return | Whether to return expanded data as output | Boolean | TRUE

### Weighting Options

In general these only affect analytic methods of 'dose-response' and 'censoring'. However, providing `cense` will allow ITT to be weighted in the case of a censoring variable like loss-to-followup.

| Option Name | Description | Input Type | Example |
|------------|-------------------------------------|------------|------------|
| weighted | Whether the analysis should be weighted | Boolean | TRUE |
| weight.upper | Upper truncation for weight values | Float | 1.0 |
| weight.lower | Lower truncation for weight values | Float | 0.0 |
| weight.p99 | Whether to truncate weights at the 99% percentile | Boolean | TRUE |
| numerator | If provided, forces numerator covariates for weight models | Char | "B1+B2\*B3+B4" |
| denominator | If provided, forces denominator covariates for weight models | Char | "C1+C2\*C3+B4" |
| weight.eligible | List of columns for eligibility in weight models with certain treatment values | List | list('we1', we2') |
| cense | Column name for censoring variable | Char | "LTFU" |
| cense.numerator | If provided, forces numerator covariates for censoring models | Char | "Z1+Z2\*Z3+Z4" |
| cense.denominator | If provided, forces denominator covariates for censoring models | Char | "A1+A2\*A3+A4" |

### Plot Options (km.curves = TRUE)

All of these can be changed after SEQuential has finished analysis - if you forget to add them, no need to stop and restart. Additionally, SEQuential will output the data used for the plot if you would like to customize it yourself through your preferred plotting software.

| Option Name | Description | Input Type | Example |
|--------------|-------------------------------|--------------|--------------|
| plot.title | Title for plot output | Char | "My Plot Title" |
| plot.subtitle | Subtitle for plot output | Char | "My Plot Subtitle" |
| plot.labels | Legend labels for output plot | List | list("Tx 0", "Tx 1") |
| plot.colors | Figure colors for output plot | List | list("red", "blue") |
| plot.type | Type of output plot ("survival", "risk", "inc") | Char | "survival" |

### Internal Options

These are internal options that change output name of covariates or the decomposition method when estimating coefficients.

| Option Name        | Description                         | Input Type | Example |
|---------------|-----------------------------|--------------|--------------|
| indicator.baseline | Identifier for baseline variables   | Char       | "\_bas" |
| indicator.squared  | Identifier for squared variables    | Char       | "\_sq"  |
| fasgtlm.method     | Method for decomposition by fastglm | Integer    | 3L      |
